import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';

export interface InvoiceItem {
  id: string;
  invoice_id: string;
  description: string;
  quantity: number;
  unit_price: number;
  total: number;
}

export interface Invoice {
  id: string;
  invoice_number: string;
  guest_id: string;
  reservation_id?: string;
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  due_date?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  guests?: {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
  };
  invoice_items?: InvoiceItem[];
}

export function useInvoices() {
  return useQuery({
    queryKey: ['invoices'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('invoices')
        .select(`
          *,
          guests (id, first_name, last_name, email),
          invoice_items (*)
        `)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as Invoice[];
    },
  });
}

export interface CreateInvoiceData {
  guestId: string;
  reservationId?: string;
  taxRate: number;
  discount: number;
  notes?: string;
  items: { description: string; quantity: number; unitPrice: number }[];
}

export function useCreateInvoice() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (invoice: CreateInvoiceData) => {
      const subtotal = invoice.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
      const taxAmount = subtotal * (invoice.taxRate / 100);
      const total = subtotal + taxAmount - invoice.discount;

      // Create the invoice - invoice_number is auto-generated by trigger
      const { data: invoiceData, error: invoiceError } = await supabase
        .from('invoices')
        .insert({
          invoice_number: `INV-${Date.now()}`, // Temporary, will be overwritten by trigger
          guest_id: invoice.guestId,
          reservation_id: invoice.reservationId || null,
          subtotal,
          tax: taxAmount,
          discount: invoice.discount,
          total,
          notes: invoice.notes || null,
          status: 'draft' as const,
        })
        .select()
        .single();
      
      if (invoiceError) throw invoiceError;

      // Create invoice items
      const items = invoice.items.map(item => ({
        invoice_id: invoiceData.id,
        description: item.description,
        quantity: item.quantity,
        unit_price: item.unitPrice,
        total: item.quantity * item.unitPrice,
      }));

      const { error: itemsError } = await supabase
        .from('invoice_items')
        .insert(items);
      
      if (itemsError) throw itemsError;

      return invoiceData;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      toast({ 
        title: 'Invoice Created', 
        description: `Invoice ${data.invoice_number} has been created.` 
      });
    },
    onError: (error: Error) => {
      toast({ title: 'Error', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateInvoiceStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: Invoice['status'] }) => {
      const { data, error } = await supabase
        .from('invoices')
        .update({ status })
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      toast({ title: 'Invoice Updated', description: 'The invoice status has been updated.' });
    },
    onError: (error: Error) => {
      toast({ title: 'Error', description: error.message, variant: 'destructive' });
    },
  });
}
